[package]
name = "syu-app-ui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde_json.workspace = true
syu-diagnostics = { path = "../syu-diagnostics" }
syu-work-model = { path = "../syu-work-model" }
syu-workbench-server = { path = "../syu-workbench-server" }
