[package]
name = "mitase-app-ui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde_json.workspace = true
mitase-diagnostics = { path = "../mitase-diagnostics" }
mitase-work-model = { path = "../mitase-work-model" }
mitase-workbench-server = { path = "../mitase-workbench-server" }
