use super::CliCommandEntry;
use crate::i18n::Locale;

pub fn cli_command_catalog(locale: Locale) -> &'static [CliCommandEntry] {
    match locale {
        Locale::En => &CLI_COMMANDS_EN,
        Locale::Ja => &CLI_COMMANDS_JA,
    }
}

static CLI_COMMANDS_EN: [CliCommandEntry; 24] = [
    CliCommandEntry {
            id: "cli.browse",
            title: "Browse spec",
            description: "Explore the spec tree.",
            invocation: "syu browse . --non-interactive",
            requires_input: false,
            mutates_files: false,
            opens_spec_browser: true,
        },
    CliCommandEntry {
            id: "cli.list",
            title: "List spec items",
            description: "List philosophies, policies, requirements, or features.",
            invocation: "syu list",
            requires_input: false,
            mutates_files: false,
            opens_spec_browser: true,
        },
    CliCommandEntry {
            id: "cli.show",
            title: "Show item",
            description: "Show one spec item by ID.",
            invocation: "syu show <id>",
            requires_input: true,
            mutates_files: false,
            opens_spec_browser: true,
        },
    CliCommandEntry {
            id: "cli.search",
            title: "Search spec",
            description: "Search spec items by text or ID.",
            invocation: "syu search <query>",
            requires_input: true,
            mutates_files: false,
            opens_spec_browser: true,
        },
    CliCommandEntry {
            id: "cli.audit",
            title: "Audit spec",
            description: "Audit the layered spec for overlap and tension.",
            invocation: "syu audit .",
            requires_input: false,
            mutates_files: false,
            opens_spec_browser: false,
        },
    CliCommandEntry {
            id: "cli.log",
            title: "Show history",
            description: "Show git history for a traced requirement or feature.",
            invocation: "syu log <id>",
            requires_input: true,
            mutates_files: false,
            opens_spec_browser: false,
        },
    CliCommandEntry {
            id: "cli.explain",
            title: "Explain selector",
            description: "Explain how an ID, file, or symbol fits the spec chain.",
            invocation: "syu explain <selector>",
            requires_input: true,
            mutates_files: false,
            opens_spec_browser: true,
        },
    CliCommandEntry {
            id: "cli.relate",
            title: "Relate selector",
            description: "Inspect the connected graph around an ID, path, symbol, or range.",
            invocation: "syu relate <selector>",
            requires_input: true,
            mutates_files: false,
            opens_spec_browser: true,
        },
    CliCommandEntry {
            id: "cli.trace",
            title: "Trace file or range",
            description: "Resolve linked specs from a traced file, symbol, or git range.",
            invocation: "syu trace <file>",
            requires_input: true,
            mutates_files: false,
            opens_spec_browser: false,
        },
    CliCommandEntry {
            id: "cli.doctor",
            title: "Run doctor",
            description: "Inspect contributor-tooling readiness.",
            invocation: "syu doctor .",
            requires_input: false,
            mutates_files: false,
            opens_spec_browser: false,
        },
    CliCommandEntry {
            id: "cli.validate",
            title: "Validate workspace",
            description: "Validate layered graph, traces, and optional fixes.",
            invocation: "syu validate .",
            requires_input: false,
            mutates_files: false,
            opens_spec_browser: false,
        },
    CliCommandEntry {
            id: "cli.report",
            title: "Render report",
            description: "Render a Markdown validation report.",
            invocation: "syu report .",
            requires_input: false,
            mutates_files: true,
            opens_spec_browser: false,
        },
    CliCommandEntry {
            id: "cli.init",
            title: "Initialize workspace",
            description: "Scaffold a version-matched syu workspace.",
            invocation: "syu init .",
            requires_input: false,
            mutates_files: true,
            opens_spec_browser: false,
        },
    CliCommandEntry {
            id: "cli.templates",
            title: "List templates",
            description: "List starter templates and examples.",
            invocation: "syu templates",
            requires_input: false,
            mutates_files: false,
            opens_spec_browser: false,
        },
    CliCommandEntry {
            id: "cli.completion",
            title: "Generate completion",
            description: "Generate shell completion scripts.",
            invocation: "syu completion <shell>",
            requires_input: true,
            mutates_files: false,
            opens_spec_browser: false,
        },
    CliCommandEntry {
            id: "cli.task.classify",
            title: "Classify request",
            description: "Classify a request artifact.",
            invocation: "syu task classify <request.yaml>",
            requires_input: true,
            mutates_files: false,
            opens_spec_browser: false,
        },
    CliCommandEntry {
            id: "cli.task.scope",
            title: "Scope request",
            description: "Map a request artifact onto the spec graph.",
            invocation: "syu task scope <request.yaml>",
            requires_input: true,
            mutates_files: false,
            opens_spec_browser: true,
        },
    CliCommandEntry {
            id: "cli.task.scaffold",
            title: "Scaffold request",
            description: "Preview spec and file updates from a request.",
            invocation: "syu task scaffold <request.yaml>",
            requires_input: true,
            mutates_files: false,
            opens_spec_browser: false,
        },
    CliCommandEntry {
            id: "cli.task.plan",
            title: "Plan request",
            description: "Generate a temporary Goal Plan.",
            invocation: "syu task plan <request.yaml>",
            requires_input: true,
            mutates_files: false,
            opens_spec_browser: false,
        },
    CliCommandEntry {
            id: "cli.task.test_select",
            title: "Select task tests",
            description: "Select tests from a Goal Plan.",
            invocation: "syu task test-select <goal-plan.yaml>",
            requires_input: true,
            mutates_files: false,
            opens_spec_browser: false,
        },
    CliCommandEntry {
            id: "cli.task.infer",
            title: "Infer task goal",
            description: "Infer a provisional Goal Plan from a git diff.",
            invocation: "syu task infer --range origin/main...HEAD",
            requires_input: false,
            mutates_files: false,
            opens_spec_browser: false,
        },
    CliCommandEntry {
            id: "cli.task.check",
            title: "Check task goal",
            description: "Validate a Goal Plan against a git range.",
            invocation: "syu task check <goal-plan.yaml>",
            requires_input: true,
            mutates_files: false,
            opens_spec_browser: false,
        },
    CliCommandEntry {
            id: "cli.add",
            title: "Add spec stub",
            description: "Scaffold a philosophy, policy, requirement, or feature stub.",
            invocation: "syu add <kind> <id>",
            requires_input: true,
            mutates_files: true,
            opens_spec_browser: false,
        },
    CliCommandEntry {
            id: "cli.lsp",
            title: "Start LSP",
            description: "Start the editor integration language server.",
            invocation: "syu lsp",
            requires_input: false,
            mutates_files: false,
            opens_spec_browser: false,
        },
];

static CLI_COMMANDS_JA: [CliCommandEntry; 24] = [
    CliCommandEntry {
        id: "cli.browse",
        title: "仕様を閲覧",
        description: "仕様ツリーをたどります。",
        invocation: "syu browse . --non-interactive",
        requires_input: false,
        mutates_files: false,
        opens_spec_browser: true,
    },
    CliCommandEntry {
        id: "cli.list",
        title: "仕様項目を一覧",
        description: "philosophy、policy、requirement、feature を並べます。",
        invocation: "syu list",
        requires_input: false,
        mutates_files: false,
        opens_spec_browser: true,
    },
    CliCommandEntry {
        id: "cli.show",
        title: "項目を表示",
        description: "ID で 1 件の仕様項目を表示します。",
        invocation: "syu show <id>",
        requires_input: true,
        mutates_files: false,
        opens_spec_browser: true,
    },
    CliCommandEntry {
        id: "cli.search",
        title: "仕様を検索",
        description: "テキストや ID で仕様項目を検索します。",
        invocation: "syu search <query>",
        requires_input: true,
        mutates_files: false,
        opens_spec_browser: true,
    },
    CliCommandEntry {
        id: "cli.audit",
        title: "仕様を監査",
        description: "重なりや緊張関係を点検します。",
        invocation: "syu audit .",
        requires_input: false,
        mutates_files: false,
        opens_spec_browser: false,
    },
    CliCommandEntry {
        id: "cli.log",
        title: "履歴を表示",
        description: "追跡された requirement や feature の git 履歴を表示します。",
        invocation: "syu log <id>",
        requires_input: true,
        mutates_files: false,
        opens_spec_browser: false,
    },
    CliCommandEntry {
        id: "cli.explain",
        title: "選択理由を説明",
        description: "ID、ファイル、シンボルが仕様の流れにどう入るかを説明します。",
        invocation: "syu explain <selector>",
        requires_input: true,
        mutates_files: false,
        opens_spec_browser: true,
    },
    CliCommandEntry {
        id: "cli.relate",
        title: "関連を表示",
        description: "ID、パス、シンボル、範囲の周辺グラフを調べます。",
        invocation: "syu relate <selector>",
        requires_input: true,
        mutates_files: false,
        opens_spec_browser: true,
    },
    CliCommandEntry {
        id: "cli.trace",
        title: "ファイル/範囲を追跡",
        description: "追跡済みのファイル、シンボル、git 範囲から関連仕様を解決します。",
        invocation: "syu trace <file>",
        requires_input: true,
        mutates_files: false,
        opens_spec_browser: false,
    },
    CliCommandEntry {
        id: "cli.doctor",
        title: "診断を実行",
        description: "開発用ツールの準備状況を確認します。",
        invocation: "syu doctor .",
        requires_input: false,
        mutates_files: false,
        opens_spec_browser: false,
    },
    CliCommandEntry {
        id: "cli.validate",
        title: "ワークスペースを検証",
        description: "層状グラフ、追跡、任意の修正を検証します。",
        invocation: "syu validate .",
        requires_input: false,
        mutates_files: false,
        opens_spec_browser: false,
    },
    CliCommandEntry {
        id: "cli.report",
        title: "レポートを生成",
        description: "Markdown の検証レポートを出力します。",
        invocation: "syu report .",
        requires_input: false,
        mutates_files: true,
        opens_spec_browser: false,
    },
    CliCommandEntry {
        id: "cli.init",
        title: "ワークスペースを初期化",
        description: "syu に合ったワークスペース雛形を作成します。",
        invocation: "syu init .",
        requires_input: false,
        mutates_files: true,
        opens_spec_browser: false,
    },
    CliCommandEntry {
        id: "cli.templates",
        title: "テンプレート一覧",
        description: "スターターテンプレートと例を一覧します。",
        invocation: "syu templates",
        requires_input: false,
        mutates_files: false,
        opens_spec_browser: false,
    },
    CliCommandEntry {
        id: "cli.completion",
        title: "補完を生成",
        description: "シェル補完スクリプトを生成します。",
        invocation: "syu completion <shell>",
        requires_input: true,
        mutates_files: false,
        opens_spec_browser: false,
    },
    CliCommandEntry {
        id: "cli.task.classify",
        title: "依頼を分類",
        description: "依頼アーティファクトを分類します。",
        invocation: "syu task classify <request.yaml>",
        requires_input: true,
        mutates_files: false,
        opens_spec_browser: false,
    },
    CliCommandEntry {
        id: "cli.task.scope",
        title: "依頼をスコープ",
        description: "依頼アーティファクトを仕様グラフへ対応付けます。",
        invocation: "syu task scope <request.yaml>",
        requires_input: true,
        mutates_files: false,
        opens_spec_browser: true,
    },
    CliCommandEntry {
        id: "cli.task.scaffold",
        title: "依頼を雛形化",
        description: "依頼から仕様とファイルの更新案をプレビューします。",
        invocation: "syu task scaffold <request.yaml>",
        requires_input: true,
        mutates_files: false,
        opens_spec_browser: false,
    },
    CliCommandEntry {
        id: "cli.task.plan",
        title: "依頼を計画化",
        description: "スコープ済み依頼から一時的な Goal Plan を生成します。",
        invocation: "syu task plan <request.yaml>",
        requires_input: true,
        mutates_files: false,
        opens_spec_browser: false,
    },
    CliCommandEntry {
        id: "cli.task.test_select",
        title: "テストを選択",
        description: "Goal Plan からテストを絞り込みます。",
        invocation: "syu task test-select <goal-plan.yaml>",
        requires_input: true,
        mutates_files: false,
        opens_spec_browser: false,
    },
    CliCommandEntry {
        id: "cli.task.infer",
        title: "ゴールを推定",
        description: "git diff から暫定 Goal Plan を推定します。",
        invocation: "syu task infer --range origin/main...HEAD",
        requires_input: false,
        mutates_files: false,
        opens_spec_browser: false,
    },
    CliCommandEntry {
        id: "cli.task.check",
        title: "ゴールを検証",
        description: "Goal Plan を git 範囲と照合します。",
        invocation: "syu task check <goal-plan.yaml>",
        requires_input: true,
        mutates_files: false,
        opens_spec_browser: false,
    },
    CliCommandEntry {
        id: "cli.add",
        title: "仕様の下書きを追加",
        description: "philosophy、policy、requirement、feature の下書きを作成します。",
        invocation: "syu add <kind> <id>",
        requires_input: true,
        mutates_files: true,
        opens_spec_browser: false,
    },
    CliCommandEntry {
        id: "cli.lsp",
        title: "LSP を起動",
        description: "エディタ連携の language server を起動します。",
        invocation: "syu lsp",
        requires_input: false,
        mutates_files: false,
        opens_spec_browser: false,
    },
];
