use super::CliCommandEntry;

pub fn cli_command_catalog() -> &'static [CliCommandEntry] {
    &[
        CliCommandEntry {
            id: "cli.browse",
            title: "Browse spec",
            description: "Explore the spec tree.",
            invocation: "syu browse . --non-interactive",
            requires_input: false,
            mutates_files: false,
            opens_spec_browser: true,
        },
        CliCommandEntry {
            id: "cli.list",
            title: "List spec items",
            description: "List philosophies, policies, requirements, or features.",
            invocation: "syu list",
            requires_input: false,
            mutates_files: false,
            opens_spec_browser: true,
        },
        CliCommandEntry {
            id: "cli.show",
            title: "Show item",
            description: "Show one spec item by ID.",
            invocation: "syu show <id>",
            requires_input: true,
            mutates_files: false,
            opens_spec_browser: true,
        },
        CliCommandEntry {
            id: "cli.search",
            title: "Search spec",
            description: "Search spec items by text or ID.",
            invocation: "syu search <query>",
            requires_input: true,
            mutates_files: false,
            opens_spec_browser: true,
        },
        CliCommandEntry {
            id: "cli.audit",
            title: "Audit spec",
            description: "Audit the layered spec for overlap and tension.",
            invocation: "syu audit .",
            requires_input: false,
            mutates_files: false,
            opens_spec_browser: false,
        },
        CliCommandEntry {
            id: "cli.log",
            title: "Show history",
            description: "Show git history for a traced requirement or feature.",
            invocation: "syu log <id>",
            requires_input: true,
            mutates_files: false,
            opens_spec_browser: false,
        },
        CliCommandEntry {
            id: "cli.explain",
            title: "Explain selector",
            description: "Explain how an ID, file, or symbol fits the spec chain.",
            invocation: "syu explain <selector>",
            requires_input: true,
            mutates_files: false,
            opens_spec_browser: true,
        },
        CliCommandEntry {
            id: "cli.relate",
            title: "Relate selector",
            description: "Inspect the connected graph around an ID, path, symbol, or range.",
            invocation: "syu relate <selector>",
            requires_input: true,
            mutates_files: false,
            opens_spec_browser: true,
        },
        CliCommandEntry {
            id: "cli.trace",
            title: "Trace file or range",
            description: "Resolve linked specs from a traced file, symbol, or git range.",
            invocation: "syu trace <file>",
            requires_input: true,
            mutates_files: false,
            opens_spec_browser: false,
        },
        CliCommandEntry {
            id: "cli.doctor",
            title: "Run doctor",
            description: "Inspect contributor-tooling readiness.",
            invocation: "syu doctor .",
            requires_input: false,
            mutates_files: false,
            opens_spec_browser: false,
        },
        CliCommandEntry {
            id: "cli.validate",
            title: "Validate workspace",
            description: "Validate layered graph, traces, and optional fixes.",
            invocation: "syu validate .",
            requires_input: false,
            mutates_files: false,
            opens_spec_browser: false,
        },
        CliCommandEntry {
            id: "cli.report",
            title: "Render report",
            description: "Render a Markdown validation report.",
            invocation: "syu report .",
            requires_input: false,
            mutates_files: true,
            opens_spec_browser: false,
        },
        CliCommandEntry {
            id: "cli.init",
            title: "Initialize workspace",
            description: "Scaffold a version-matched syu workspace.",
            invocation: "syu init .",
            requires_input: false,
            mutates_files: true,
            opens_spec_browser: false,
        },
        CliCommandEntry {
            id: "cli.templates",
            title: "List templates",
            description: "List starter templates and examples.",
            invocation: "syu templates",
            requires_input: false,
            mutates_files: false,
            opens_spec_browser: false,
        },
        CliCommandEntry {
            id: "cli.completion",
            title: "Generate completion",
            description: "Generate shell completion scripts.",
            invocation: "syu completion <shell>",
            requires_input: true,
            mutates_files: false,
            opens_spec_browser: false,
        },
        CliCommandEntry {
            id: "cli.task.classify",
            title: "Classify request",
            description: "Classify a request artifact.",
            invocation: "syu task classify <request.yaml>",
            requires_input: true,
            mutates_files: false,
            opens_spec_browser: false,
        },
        CliCommandEntry {
            id: "cli.task.scope",
            title: "Scope request",
            description: "Map a request artifact onto the spec graph.",
            invocation: "syu task scope <request.yaml>",
            requires_input: true,
            mutates_files: false,
            opens_spec_browser: true,
        },
        CliCommandEntry {
            id: "cli.task.scaffold",
            title: "Scaffold request",
            description: "Preview spec and file updates from a request.",
            invocation: "syu task scaffold <request.yaml>",
            requires_input: true,
            mutates_files: false,
            opens_spec_browser: false,
        },
        CliCommandEntry {
            id: "cli.task.plan",
            title: "Plan request",
            description: "Generate a temporary Goal Plan.",
            invocation: "syu task plan <request.yaml>",
            requires_input: true,
            mutates_files: false,
            opens_spec_browser: false,
        },
        CliCommandEntry {
            id: "cli.task.test_select",
            title: "Select task tests",
            description: "Select tests from a Goal Plan.",
            invocation: "syu task test-select <goal-plan.yaml>",
            requires_input: true,
            mutates_files: false,
            opens_spec_browser: false,
        },
        CliCommandEntry {
            id: "cli.task.infer",
            title: "Infer task goal",
            description: "Infer a provisional Goal Plan from a git diff.",
            invocation: "syu task infer --range origin/main...HEAD",
            requires_input: false,
            mutates_files: false,
            opens_spec_browser: false,
        },
        CliCommandEntry {
            id: "cli.task.check",
            title: "Check task goal",
            description: "Validate a Goal Plan against a git range.",
            invocation: "syu task check <goal-plan.yaml>",
            requires_input: true,
            mutates_files: false,
            opens_spec_browser: false,
        },
        CliCommandEntry {
            id: "cli.add",
            title: "Add spec stub",
            description: "Scaffold a philosophy, policy, requirement, or feature stub.",
            invocation: "syu add <kind> <id>",
            requires_input: true,
            mutates_files: true,
            opens_spec_browser: false,
        },
        CliCommandEntry {
            id: "cli.lsp",
            title: "Start LSP",
            description: "Start the editor integration language server.",
            invocation: "syu lsp",
            requires_input: false,
            mutates_files: false,
            opens_spec_browser: false,
        },
    ]
}
