[package]
name = "mitase-delivery"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
sha2.workspace = true
tempfile.workspace = true
fs2.workspace = true
uuid.workspace = true
mitase-work-model = { path = "../mitase-work-model" }
mitase-spec-model = { path = "../mitase-spec-model" }
mitase-planner = { path = "../mitase-planner" }
mitase-workspace = { path = "../mitase-workspace" }
mitase-validation = { path = "../mitase-validation" }
