// FEAT-DOCS-002

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  // The docs tree is the sidebar: user-facing folders and their index pages
  // are the single source of truth for navigation.
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }]
};
